#!/bin/bash

# Unmanned Manager - Setup Script
# This script helps you configure your AI assistant

echo "========================================"
echo "  Unmanned Manager Setup"
echo "  'At your service.'"
echo "========================================"
echo ""

# Get user name
read -p "What's your name? " USER_NAME
if [ -z "$USER_NAME" ]; then
    USER_NAME="User"
fi

# Get honorific preference
echo ""
echo "How should your AI assistant address you?"
echo "  1) sir"
echo "  2) boss"
echo "  3) chief"
echo "  4) Just my name"
echo "  5) Custom"
read -p "Choose (1-5): " HONORIFIC_CHOICE

case $HONORIFIC_CHOICE in
    1) HONORIFIC="sir" ;;
    2) HONORIFIC="boss" ;;
    3) HONORIFIC="chief" ;;
    4) HONORIFIC="$USER_NAME" ;;
    5) read -p "Enter custom honorific: " HONORIFIC ;;
    *) HONORIFIC="sir" ;;
esac

# Get project path
echo ""
read -p "Path to your projects folder (e.g., /Users/you/projects): " PROJECT_PATH
if [ -z "$PROJECT_PATH" ]; then
    PROJECT_PATH="/path/to/your/projects"
fi

# Get language preference
echo ""
echo "Preferred language?"
echo "  1) English (en)"
echo "  2) Korean (ko)"
echo "  3) Japanese (ja)"
read -p "Choose (1-3): " LANG_CHOICE

case $LANG_CHOICE in
    1) LANGUAGE="en" ;;
    2) LANGUAGE="ko" ;;
    3) LANGUAGE="ja" ;;
    *) LANGUAGE="en" ;;
esac

# Update config.yaml
echo ""
echo "Updating config.yaml..."

cat > config.yaml << EOF
# Unmanned Manager Configuration
# Generated by setup.sh on $(date +%Y-%m-%d)

# ============================================
# User Settings
# ============================================
user:
  name: "$USER_NAME"
  honorific: "$HONORIFIC"
  timezone: "$(cat /etc/timezone 2>/dev/null || echo "UTC")"

# ============================================
# Project Monitoring
# ============================================
projects:
  git_scan_enabled: true
  scan_paths:
    - "$PROJECT_PATH"
  inactive_alert_days: 7

# ============================================
# Briefing Settings
# ============================================
briefing:
  deadline_alert_days: 3
  show_git_status: true
  show_recent_commits: true

# ============================================
# Shadow Counselor (Optional)
# ============================================
shadow_counselor:
  enabled: true
  record_observations: true

# ============================================
# Communication Style
# ============================================
communication:
  language: "$LANGUAGE"
  style: "formal"
  prefer_structured: true
  concise: true
EOF

echo "Done!"
echo ""
echo "========================================"
echo "  Setup Complete!"
echo "========================================"
echo ""
echo "Your settings:"
echo "  Name: $USER_NAME"
echo "  Honorific: $HONORIFIC"
echo "  Projects: $PROJECT_PATH"
echo "  Language: $LANGUAGE"
echo ""
echo "Next steps:"
echo "  1. Review config.yaml if you want to change anything"
echo "  2. Add your projects to current/projects.md"
echo "  3. Open Claude Code: claude"
echo "  4. Type '와썹' to start"
echo ""
echo "At your service, $HONORIFIC."
